acceptedOnly: false
fallbackTitle: webclip.%date
file: ''
html: false
includeComments: false
includeSource: true
includeTitle: true
inlineLinks: true
metadata: true
metadataYaml: false
minUpvotes: 0
nvAdd: false
nvUrl: false
nvuAdd: false
nvuNotebook: ''
nvuUrl: false
paragraphLinks: false
paste: false
readability: true
stdin: false
titleOnly: false
unicode: true
urlOpen: true
urlTemplate: obsidian://new?vault=digital-brain&file=%2Binbox%2Fwebclip.%filename&content=%text
