#!/usr/bin/env zsh

function colormap() {
  echo -e "\n\e[1m\e[4m\e[7m 8-bit colors \e[0m\n"
  for code in {30..37}; do \
  echo -en "\e[${code}m"'\\e['"$code"'m'"\e[0m"; \
  echo -en "  \e[$code;1m"'\\e['"$code"';1m'"\e[0m"; \
  echo -en "  \e[$code;3m"'\\e['"$code"';3m'"\e[0m"; \
  echo -en "  \e[$code;4m"'\\e['"$code"';4m'"\e[0m"; \
  echo -e "  \e[$((code+60))m"'\\e['"$((code+60))"'m'"\e[0m"; \
  done
  echo -e "\n\e[1m\e[4m\e[7m 24-bit colors \e[0m\n"
  for i in {0..255}; do print -Pn "%K{$i}  %k%F{$i}${(l:3::0:)i}%f " ${${(M)$((i%6)):#3}:+$'\n'}; done
}
