#!/usr/bin/env zsh

# Stages all changes and creates a new commit in Git with the given message.
# Usage: gg "Commit message"
function gg() {
  if ! git add .; then
    echo "Failed to stage changes."
    return 1
  fi

  if ! git commit -m "$1"; then
    echo "Failed to create commit."
    return 1
  fi
}
