#!/usr/bin/env zsh

# This script generates Obsidian plugin metadata files for all plugins in a directory.
import_obsidian_plugins() {

  # Define the directory containing the plugins.
  PLUGIN_DIR="$HOME/git/andrewmcodes/digital-brain/.obsidian/plugins"

  # Loop through each plugin directory.
  for plugin_dir in "$PLUGIN_DIR"/*; do
    # Get the path to the manifest file.
    manifest_file="$plugin_dir/manifest.json"

    # Check if the manifest file exists.
    if [ ! -f "$manifest_file" ]; then
      echo "Manifest file not found: $manifest_file"
      continue
    fi

    # Parse the manifest file to get the plugin metadata.
    id=$(jq -r '.id' "$manifest_file")
    clean_id=${id#obsidian-}
    name=$(jq -r '.name' "$manifest_file")
    description=$(jq -r '.description' "$manifest_file")
    author=$(jq -r '.author' "$manifest_file")
    author_url=$(jq -r '.authorUrl' "$manifest_file")

    # Generate the metadata file content.
    md_content=$(printf -- '---
type: extension
aliases:
  - "%s"
description: "%s"
category:
author:
  - "[[%s]]"
links:
  - "%s"
  - "https://obsidian-plugin-stats.vercel.app/plugins/%s"
  - "obsidian://show-plugin?id=%s"
collection:
  - "[[VSCode Extensions]]"
---
' "$name" "$description" "$author" "$author_url" "$id" "$id")

    # Write the metadata file.
    md_file="$HOME/git/andrewmcodes/digital-brain/objects/Extensions/ext.obsidian.$clean_id.md"
    echo "Creating $md_file"
    echo "$md_content" >|"$md_file"
  done

}
