#!/usr/bin/env zsh

# Start the Overmind process manager with the appropriate Procfile
#
# If a Procfile.andrew file exists in the current directory, use that file.
# Otherwise, use the default Procfile.dev file.
#
# Usage: os [--any-can-die]
function os() {
  local any_can_die=""
  if [ "$1" = "--any-can-die" ]; then
    any_can_die="--any-can-die"
  fi

  if [ -f Procfile.andrew ]; then
    overmind start $any_can_die -f Procfile.andrew -D -p 3000 -P 1
  else
    overmind start $any_can_die -f Procfile.dev -D -p 3000 -P 1
  fi
}
