#!/usr/bin/env zsh

function pg_switch {
  local version_to_run=$1
  local currently_running_version=$(psql --no-psqlrc -t -c 'show server_version;' postgres | xargs)

  # check if you're erroneously switching to the same version
  if [ "$version_to_run" = "$currently_running_version" ]; then
    echo "Postgres $version_to_run is already running."
    return 1
  fi

  echo Switching from $currently_running_version to $version_to_run
  # stop the currently running postgres server
  $HOME/.asdf/installs/postgres/$currently_running_version/bin/pg_ctl \
    -D $HOME/.asdf/installs/postgres/$currently_running_version/data \
    stop
  # start the server to be started
  $HOME/.asdf/installs/postgres/$version_to_run/bin/pg_ctl \
    -D $HOME/.asdf/installs/postgres/$version_to_run/data \
    start
  # switch the global asdf version, this ensures that `psql` is shimmed to the right version-directory
  asdf global postgres $version_to_run
}
