#!/usr/bin/env zsh

function rails() {
  if [[ -f bin/rails ]]; then
    bin/rails $@
  elif [[ -f Gemfile && -f Gemfile.lock ]]; then
    bundle exec rails $@
  elif [[ -n $(which rails) ]]; then
    command rails $@
  else
    echo "Rails not found"
  fi
}
