#!/usr/bin/env zsh

# Arguments:
# $1: The command to search for
# $2: The action to take
#   --note: Save the note in a file
#   --copy: Copy the note to the clipboard
#  (default): Print the note to the terminal
# Example: tldrformat git --note
function tldrformat() {
  # Run the tldr command and save the output in a variable
  tldr_output=$(tldr "$1" | sed 's/\x1b\[[0-9;]*m//g')

  # If the first line contains "This page doesn't exist yet", exit
  if [[ $(echo "$tldr_output" | head -n 1) == *"This page doesn't exist yet"* ]]; then
    exit 1
  fi

  # Extract the description, starting from line 4 and ending before the link
  description=$(echo "$tldr_output" | awk 'NR>=4 && /^More information/{exit} {print}')
  # The link will always start with `More information`.
  link=$(echo "$tldr_output" | awk '/^More information/ {print}')
  # Save the new note in a variable, starting with the description and the link
  note="$description\n\n- b $link\n\n## TL;DR\n"

  # Iterate over the tldr output, starting from line 6
  while IFS= read -r line; do
    # If the line starts with a -, it's a command description
    if [[ $line == -* ]]; then
      note="$note\n### ${line:2}\n"
    # If the line is empty, skip it
    elif [[ -z "$line" ]]; then
      continue
    # If the line starts with 4 spaces, it's a code block
    elif [[ $line == "   "* ]]; then
      note="$note\n\`\`\`shell\n${line:4}\n\`\`\`\n"
    fi
  done < <(echo "$tldr_output" | awk 'NR>6')

  if [[ $2 == "--note" ]]; then
    # Save the note in a file
    echo -e "$note" > "$HOME/git/andrewmcodes/digital-brain/term.cli.$1.md"
    # If the note was saved successfully, show a notification
    if [[ $? == 0 ]]; then
      osascript -e 'display notification "TLDR saved to file" with title "tldrformat"'
    else
      osascript -e 'display notification "TLDR failed to save to file" with title "tldrformat"'
    fi
  elif [[ $2 == "--copy" ]]; then
    # Copy the note to the clipboard
    echo -e "$note" | xclip -selection clipboard
    osascript -e 'display notification "TLDR copied to clipboard" with title "tldrformat"'
  else
    echo -e "$note"
  fi
}
